files:
  - source: /**/eventTextCs*.json
    translation: /crowdin/%language%/%original_file_name%
    type: json
    update_option: update_as_unapproved
    escape_quotes: 3
    multilingual: 
    source_language: ja
    json:
      content_key: "*"
      structure: "{id}"
