files:
  - source: /**/eventTextCs*.json
    translation: /crowdin/%language%/%original_file_name%
    type: json
    update_option: update_as_unapproved
    translation_replace:
      - ''
      - ''
      - ''
